// @ts-check

import fs from 'node:fs';
import path from 'node:path';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import { defineConfig, fontProviders } from 'astro/config';

import tailwindcss from '@tailwindcss/vite';

// Build 301-style redirects from the old (pre-restructure) URLs to the new
// category routes. Generated by scanning the content dirs so every old article
// URL maps to its correct new home (analysis routed by `league`).
const LANGS = ['zh-tw', 'en', 'th', 'bn'];
function buildRedirects() {
  const r = {};
  for (const lang of LANGS) {
    r[`/${lang}/analysis`] = `/${lang}/football/world-cup/analysis`;
    r[`/${lang}/guides`] = `/${lang}/football/world-cup/guides`;
    r[`/${lang}/bracket`] = `/${lang}/football/world-cup/bracket`;
    r[`/${lang}/group-stage`] = `/${lang}/football/world-cup/group-stage`;
    r[`/${lang}/schedule`] = `/${lang}/football/world-cup/schedule`;
    // MLB was retired in favor of cricket — send any already-indexed old URLs
    // to their closest new equivalent.
    r[`/${lang}/mlb`] = `/${lang}/cricket`;
    r[`/${lang}/mlb/guides`] = `/${lang}/cricket/guides`;

    // These two started out in `trends` before match-specific analysis was
    // split into its own `matchAnalysis` collection/route — redirect their
    // old URLs in case they were already shared or indexed.
    for (const slug of ['epl-matchweek-1-review', 'man-city-matchweek-2-analysis']) {
      r[`/${lang}/football/leagues/trends/${slug}`] = `/${lang}/football/leagues/analysis/${slug}`;
    }

    const aDir = path.resolve(`src/content/analysis/${lang}`);
    if (fs.existsSync(aDir)) {
      for (const file of fs.readdirSync(aDir)) {
        if (!/\.(md|mdx)$/.test(file)) continue;
        const slug = file.replace(/\.(md|mdx)$/, '');
        const src = fs.readFileSync(path.join(aDir, file), 'utf8');
        if (/^draft:\s*true/m.test(src)) continue;
        const m = src.match(/^league:\s*(\S+)/m);
        const league = m ? m[1] : 'world-cup';
        const dest = league === 'nba' ? `/${lang}/nba/analysis/${slug}`
          : league === 'cricket' ? `/${lang}/cricket/analysis/${slug}`
          : `/${lang}/football/world-cup/analysis/${slug}`;
        r[`/${lang}/analysis/${slug}`] = dest;
      }
    }
    const gDir = path.resolve(`src/content/guides/${lang}`);
    if (fs.existsSync(gDir)) {
      for (const file of fs.readdirSync(gDir)) {
        if (!/\.(md|mdx)$/.test(file)) continue;
        const slug = file.replace(/\.(md|mdx)$/, '');
        const src = fs.readFileSync(path.join(gDir, file), 'utf8');
        const m = src.match(/^sport:\s*(\S+)/m);
        const sport = m ? m[1] : 'football';
        const lm = src.match(/^league:\s*(\S+)/m);
        const guideLeague = lm ? lm[1] : 'world-cup';
        const dest = sport === 'cricket' ? `/${lang}/cricket/guides/${slug}`
          : sport === 'basketball' ? `/${lang}/nba/guides/${slug}`
          : guideLeague === 'club-football' ? `/${lang}/football/leagues/guides/${slug}`
          : `/${lang}/football/world-cup/guides/${slug}`;
        r[`/${lang}/guides/${slug}`] = dest;
      }
    }
  }
  return r;
}
const redirects = buildRedirects();

// https://astro.build/config
export default defineConfig({
  site: 'https://thebigbet.org',
  redirects,
  i18n: {
    defaultLocale: 'zh-tw',
    locales: ['zh-tw', 'en', 'th', 'bn'],
  },
  integrations: [mdx(), sitemap()],

  fonts: [
      {
          provider: fontProviders.local(),
          name: 'Atkinson',
          cssVariable: '--font-atkinson',
          fallbacks: ['sans-serif'],
          options: {
              variants: [
                  {
                      src: ['./src/assets/fonts/atkinson-regular.woff'],
                      weight: 400,
                      style: 'normal',
                      display: 'swap',
                  },
                  {
                      src: ['./src/assets/fonts/atkinson-bold.woff'],
                      weight: 700,
                      style: 'normal',
                      display: 'swap',
                  },
              ],
          },
      },
	],

  vite: {
    plugins: [tailwindcss()],
  },
});